apiVersion: v2
name: cloudkitty
description: A Helm chart for Openstack Cloudkitty
type: application
version: 2.0.0
appVersion: "20.0.0-10-g7ac42dd-2"
sources:
  - https://github.com/NeCTAR-RC/cloudkitty-helm.git
dependencies:
- name: redis
  version: 19.6.1
  repository: https://charts.bitnami.com/bitnami
  condition: components.redis
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
- name: nectarlib
  version: 1.7.2
  repository: oci://registry.rc.nectar.org.au/nectar-helm
