apiVersion: v2
name: cloudkitty
description: A Helm chart for Openstack Cloudkitty
type: application
version: 3.0.0
appVersion: "22.0.0-10-g44288d7-2-8"
sources:
  - https://github.com/NeCTAR-RC/cloudkitty-helm.git
dependencies:
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 23.2.2
  condition: components.redis
- name: nectarlib
  version: 3.2.0
  repository: oci://registry.rc.nectar.org.au/nectar-helm
