apiVersion: v2
name: cloudkitty
description: A Helm chart for Openstack Cloudkitty
type: application
version: 2.6.1
appVersion: "20.0.0-11-gd5bbc9e-3"
sources:
  - https://github.com/NeCTAR-RC/cloudkitty-helm.git
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.23.0
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 19.6.4
  condition: components.redis
- name: nectarlib
  version: 1.7.8
  repository: oci://registry.rc.nectar.org.au/nectar-helm
