apiVersion: v2
name: cloudkitty
description: A Helm chart for Openstack Cloudkitty
type: application
version: 1.16.0
appVersion: "wallaby"
sources:
  - https://github.com/NeCTAR-RC/cloudkitty-helm.git
dependencies:
- name: redis
  version: 19.6.0
  repository: https://charts.bitnami.com/bitnami
  condition: components.redis
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
