apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudkitty.fullname" . }}-api
  labels:
    {{- include "cloudkitty.labels" . | nindent 4 }}
data:
  apache.conf: |
    Listen 0.0.0.0:8889

    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy

    SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
    CustomLog /dev/stdout combined env=!forwarded
    CustomLog /dev/stdout proxy env=forwarded

    <VirtualHost *:8889>
        WSGIDaemonProcess cloudkitty processes=8 threads=8 user=cloudkitty group=cloudkitty display-name=%{GROUP}
        WSGIProcessGroup cloudkitty
        WSGIScriptAlias / /usr/lib/cgi-bin/cloudkitty-api
        WSGIApplicationGroup %{GLOBAL}
        WSGIPassAuthorization On
        LimitRequestBody 114688
        <IfVersion >= 2.4>
          ErrorLogFormat "%{cu}t %M"
        </IfVersion>
        ErrorLog /dev/stdout

        <Directory /usr/lib/cgi-bin>
            <IfVersion >= 2.4>
                Require all granted
            </IfVersion>
            <IfVersion < 2.4>
                Order allow,deny
                Allow from all
            </IfVersion>
        </Directory>

        SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
        CustomLog /dev/stdout combined env=!forwarded
        CustomLog /dev/stdout proxy env=forwarded
    </VirtualHost>
  config.json: |
    {
        "command": "/usr/sbin/apache2 -DFOREGROUND",
        "config_files": [
            {
                "source": "/var/lib/kolla/venv/bin/cloudkitty-api",
                "dest": "/usr/lib/cgi-bin/cloudkitty-api",
                "owner": "cloudkitty:cloudkitty",
                "perm": "0640",
                "optional": false
            },
            {
                "source": "/var/lib/kolla/config_files/apache.conf",
                "dest": "/etc/apache2/conf-enabled/10-cloudkitty_wsgi.conf",
                "owner": "cloudkitty:cloudkitty",
                "perm": "0640",
                "optional": false
            },
            {
                "source": "/vault/secrets/secrets.conf",
                "dest": "/etc/cloudkitty/cloudkitty.conf.d/secrets.conf",
                "owner": "cloudkitty:cloudkitty",
                "perm": "0600",
                "optional": false
            }
        ]
    }
