{{- include "nectarlib.configmap" (list . "cloudkitty.configmap") -}}
{{- define "cloudkitty.configmap" -}}
data:
  api_paste.ini: |-
    [pipeline:cloudkitty+noauth]
    pipeline = cors healthcheck http_proxy_to_wsgi request_id ck_api

    [pipeline:cloudkitty+keystone]
    pipeline = cors healthcheck http_proxy_to_wsgi request_id authtoken ck_api

    [app:ck_api]
    paste.app_factory = cloudkitty.api.app:app_factory

    [filter:authtoken]
    acl_public_routes = /, /v1, /healthcheck
    paste.filter_factory = cloudkitty.api.middleware:AuthTokenMiddleware.factory

    [filter:request_id]
    paste.filter_factory = oslo_middleware:RequestId.factory

    [filter:cors]
    paste.filter_factory =  oslo_middleware.cors:filter_factory
    oslo_config_project = cloudkitty

    [filter:healthcheck]
    paste.filter_factory = oslo_middleware:Healthcheck.factory
    backends = disable_by_file
    disable_by_file_path = /etc/cloudkitty/healthcheck_disable

    [filter:http_proxy_to_wsgi]
    paste.filter_factory = oslo_middleware.http_proxy_to_wsgi:HTTPProxyToWSGI.factory
    oslo_config_project = cloudkitty
  metrics.yml: |-
    metrics:
      vcpus:
        unit: instance
        alt_name: instance
        groupby:
          - id
          - user_id
          - project_id
        metadata:
          - flavor_name
          - flavor_id
          - availability_zone
          - image_ref
        mutate: NUMBOOL
        extra_args:
          aggregation_method: mean
          resource_type: instance
      warre.reservation.exists:
        unit: reservation
        alt_name: reservation
        groupby:
          - id
          - user_id
          - project_id
        metadata:
          - flavor_name
          - flavor_id
        mutate: NUMBOOL
        extra_args:
          aggregation_method: mean
          resource_type: reservation
      loadbalancer:
        unit: loadbalancer
        alt_name: load_balancer
        groupby:
          - id
          - user_id
          - project_id
        mutate: NUMBOOL
        extra_args:
          aggregation_method: mean
          resource_type: load_balancer
      database:
        unit: database
        alt_name: database
        groupby:
          - id
          - user_id
          - project_id
        metadata:
          - flavor_id
        mutate: NUMBOOL
        extra_args:
          aggregation_method: mean
          resource_type: database
{{- end -}}
