apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudkitty-api
  labels:
    {{- include "cloudkitty.labels" . | nindent 4 }}
    app.kubernetes.io/component: cloudkitty-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudkitty.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cloudkitty-api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-map-etc.yaml") . | sha256sum }}
        {{- include "cloudkitty.vaultAnnotations" . | nindent 8 }}
      labels:
        {{- include "cloudkitty.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cloudkitty-api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cloudkitty.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.api.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: KOLLA_CONFIG_STRATEGY
          value: "COPY_ALWAYS"
        ports:
          - name: http
            containerPort: 8889
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: http
        startupProbe:
          httpGet:
            path: /healthcheck
            port: http
          initialDelaySeconds: 10
        volumeMounts:
          - name: {{ include "cloudkitty.fullname" . }}-etc
            mountPath: "/etc/cloudkitty/api_paste.ini"
            subPath: api_paste.ini
          - name: {{ include "cloudkitty.fullname" . }}-etc
            mountPath: "/etc/cloudkitty/metrics.yml"
            subPath: metrics.yml
          - name: {{ include "cloudkitty.fullname" . }}-etc
            mountPath: "/etc/cloudkitty/policy.yaml"
            subPath: policy.yaml
          - name: {{ include "cloudkitty.fullname" . }}-etc
            mountPath: "/etc/cloudkitty/cloudkitty.conf.d/cloudkitty.conf"
            subPath: cloudkitty.conf
          - name: {{ include "cloudkitty.fullname" . }}-api
            mountPath: "/var/lib/kolla/config_files/"
      volumes:
      - name: {{ include "cloudkitty.fullname" . }}-etc
        configMap:
          name: {{ include "cloudkitty.fullname" . }}-etc
      - name: {{ include "cloudkitty.fullname" . }}-api
        configMap:
          name: {{ include "cloudkitty.fullname" . }}-api
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
