{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cloudkitty.fullname" . }}-api
  labels:
    {{- include "cloudkitty.labels" . | nindent 4 }}
    app.kubernetes.io/component: cloudkitty-api
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable | default 0 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "cloudkitty.fullname" . }}
      app.kubernetes.io/component: cloudkitty-api
{{- end }}
