apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudkitty.fullname" . }}
  labels:
    {{- include "cloudkitty.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8889
      protocol: TCP
      name: http
  selector:
    {{- include "cloudkitty.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cloudkitty-api
